# Generated by Django 5.2.2 on 2025-06-17 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_text', models.TextField(verbose_name='Напоминание: Необходимо выполнить <django.db.models.query_utils.DeferredAttribute object at 0x00000209ADDB00D0> в <django.db.models.query_utils.DeferredAttribute object at 0x00000209ADDB0090> в <django.db.models.query_utils.DeferredAttribute object at 0x00000209ADDA7F90>')),
                ('award_text', models.TextField(verbose_name='После выполнения получите награду: <django.db.models.query_utils.DeferredAttribute object at 0x00000209ADDB0410>')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits_reminder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Телеграм напоминание',
            },
        ),
    ]
