# Generated by Django 5.2.2 on 2025-06-07 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_message', models.TextField(verbose_name='После выполнения получите награду: <django.db.models.query_utils.DeferredAttribute object at 0x000001D4EC3E6AD0>')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits_reminder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Телеграм напоминание',
            },
        ),
    ]
