# Generated by Django 5.2.2 on 2025-06-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_reminder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramreminder',
            name='award_message',
        ),
        migrations.AddField(
            model_name='telegramreminder',
            name='award_text',
            field=models.TextField(default=1, verbose_name='После выполнения получите награду: <django.db.models.query_utils.DeferredAttribute object at 0x00000206AC8904D0>'),
            preserve_default=False,
        ),
    ]
